spring.application.name=pizza-backend

# Cổng chạy server
server.port=8080

# Thông tin kết nối Database
spring.datasource.url=jdbc:postgresql://localhost:5432/pizza_db
spring.datasource.username=postgres
spring.datasource.password=luthanh102
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình tự động tạo bảng (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
